name: manage-azure-policy-8d9ea0e6
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Deny_NSG_ports_with_inbound_ports_blocking_cf7e83a6-3a66-4770-b389-70f8d3a5032a/**'
#      - .github/workflows/manage-azure-policy-8d9ea0e6.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_8d9ea0e6}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Deny_NSG_ports_with_inbound_ports_blocking_cf7e83a6-3a66-4770-b389-70f8d3a5032a/**
